---
# file: tasks/main.yml

# Install cron 

# Cron should run every minute

  # Try pinging aws api servers until it works

  # Once it does, run only one ansible-pull

  # The ansible-pull should include a seconds-of-sleep variable 
  #   (default should be 17 minutes of sleep)



  # run-one bash -c 'ping -c1 -w30 4.2.2.2 > /dev/null && date>> blah && sleep 10'


  # ansible-pull
  #   --purge
  #   --force
  #   --directory /var/ansible-pull
  #   --url
  #   --checkout
  #   --inventory-file
  #   --module-name git
 
# Store the git checkout on a ramdisk for security ? 
#   do not use any tmpfs, because it swaps out to disk
#   maybe a manually created ramdisk

# a suggestion from irc:

# create dir at /dev/shm/blah and disable swap because tmpfs swaps


#- name: 'install: ansible (pull): update apt cache'
#  apt: update_cache=yes
#  when: ansible_apt_repository.changed == True

#- name: 'install: ansible (pull)'
#  apt: pkg={{ item }}
#       state=present
#  with_items:
#    - ansible
