---
# file: tasks/main.yml
# 
# KnoesOS -- A warehouse scale operating system for the ages.
#
# Copyright 2013 Kno.e.sis (http://knoesis.org), Joshua Dotson <josh@wrale.com>
#
#    KnoesOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    KnoesOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with KnoesOS.  If not, see <http://www.gnu.org/licenses/>.

- name: 'install: ansible (pull): upstart default file'
  template: src=etc/default/ansible-pull.j2
            dest=/etc/init/ansible-pull.conf
            owner=root
            group=root
            mode=00700

- name: 'install: ansible (pull): upstart service job'
  template: src=etc/init/ansible-pull.conf.j2
            dest=/etc/init/ansible-pull.conf
            owner=root
            group=root
            mode=00700

# Don't forget to enable the ansible-pull service job in the default file
