---
# file: defaults/main.yml

# Location of the ansible-pull command
ANSIBLE_PULL_BIN: "/usr/bin/ansible-pull"

# host to ping to test WAN connectivity
ANSIBLE_PULL_PING_HOST: "127.0.0.1"

# where to stage pull data
ANSIBLE_PULL_STAGING_DIRECTORY: "/var/ansible-pull"

# where to obtain pull data
ANSIBLE_PULL_REPO: "YOUR_REPO_HERE"

# branch to checkout
ANSIBLE_PULL_BRANCH: "master"

# name of target inventory file
ANSIBLE_PULL_INVENTORY_FILE: "local.yml"

# Ansible module used for pull (e.g. "git")
ANSIBLE_PULL_MODULE_NAME: "git"

# Seconds to sleep between pulls (e.g. "600")
ANSIBLE_PULL_SLEEP_SECONDS: "600"

# Options to pass to ansible-pull
ANSIBLE_PULL_OPTS: >
  --purge 
  --directory $ANSIBLE_PULL_STAGING_DIRECTORY 
  --url $ANSIBLE_PULL_REPO 
  --checkout $ANSIBLE_PULL_BRANCH 
  --inventory-file $ANSIBLE_PULL_INVENTORY_FILE 
  --module-name $ANSIBLE_PULL_MODULE_NAME
