---
# file: tasks/main.yml

- name: "group_by: distribution"
  action: group_by
          key={{ ansible_distribution }}

- name: "group_by: architecture"
  action: group_by
          key={{ ansible_architecture }}

- name: "group_by: distribution-architecture"
  action: group_by
          key={{ ansible_distribution }}-{{ ansible_architecture }}

- name: "group_by: distribution-version"
  action: group_by
          key={{ ansible_distribution }}-{{ ansible_distribution_version }}

- name: "group_by: distribution-version-architecture"
  action: group_by
          key={{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}
